-- 创建碗碟转卖记录表
CREATE TABLE IF NOT EXISTS `dishware_transfer_records` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `dishware_id` INT NOT NULL COMMENT '碗碟ID',
    `from_restaurant_id` INT NOT NULL COMMENT '转出餐厅ID',
    `to_restaurant_id` INT NOT NULL COMMENT '转入餐厅ID',
    `from_shop_type` VARCHAR(50) NOT NULL COMMENT '转出餐厅类型（如j1）',
    `to_shop_type` VARCHAR(50) NOT NULL COMMENT '转入餐厅类型（如j3）',
    `quantity` INT NOT NULL DEFAULT 0 COMMENT '转卖数量',
    `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '单价',
    `total_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '总价',
    `transfer_date` DATE NOT NULL COMMENT '转卖日期',
    `record_type` ENUM('out', 'in') NOT NULL COMMENT '记录类型：out=出货，in=进货',
    `related_record_id` INT DEFAULT NULL COMMENT '关联记录ID（进货记录关联出货记录）',
    `recorded_by` VARCHAR(100) DEFAULT 'system' COMMENT '记录人',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`dishware_id`) REFERENCES `dishware_info`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`from_restaurant_id`) REFERENCES `dishware_restaurant_locations`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`to_restaurant_id`) REFERENCES `dishware_restaurant_locations`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`related_record_id`) REFERENCES `dishware_transfer_records`(`id`) ON DELETE CASCADE,
    INDEX `idx_dishware_id` (`dishware_id`),
    INDEX `idx_from_restaurant` (`from_restaurant_id`),
    INDEX `idx_to_restaurant` (`to_restaurant_id`),
    INDEX `idx_from_shop_type` (`from_shop_type`),
    INDEX `idx_to_shop_type` (`to_shop_type`),
    INDEX `idx_record_type` (`record_type`),
    INDEX `idx_transfer_date` (`transfer_date`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_related_record` (`related_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='碗碟转卖记录表';
