-- 创建菜单成本数据表
CREATE TABLE IF NOT EXISTS menu_cost_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL COMMENT '原材料名称',
    price DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '价格',
    unit DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '单位',
    specification VARCHAR(255) DEFAULT '' COMMENT '规格',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_product_name (product_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

