CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    username_cn VARCHAR(255) NULL,
    nickname VARCHAR(255) NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    ic_number VARCHAR(20) NULL,
    position VARCHAR(255) NULL,
    bank_name VARCHAR(255) NULL,
    bank_account VARCHAR(255) NULL,
    phone_number VARCHAR(50) NULL,
    home_address TEXT NULL,
    current_address TEXT NULL,
    city VARCHAR(100) NULL,
    state VARCHAR(100) NULL,
    postcode VARCHAR(20) NULL,
    date_of_birth DATE NULL,
    gender VARCHAR(20) NULL,
    nationality VARCHAR(100) NULL,
    race VARCHAR(100) NULL,
    emergency_contact_name VARCHAR(255) NULL,
    emergency_phone_number VARCHAR(50) NULL,
    bank_account_holder_en VARCHAR(255) NULL,
    account_type VARCHAR(50) NULL,
    registration_code VARCHAR(50) NULL,
    branch VARCHAR(50) NULL,
    is_first_login TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
