export const ACCOUNT_TYPE_ORDER = {
  special: 1,
  hr: 2,
  account: 3,
  media: 4,
  marketing: 5,
  support: 6,
  production: 7,
  'r&d': 8,
  technical: 9,
  design: 10,
  operation: 11,
  service: 12,
  sushi: 13,
  kitchen: 14,
};

export const POSITIONS_BY_ACCOUNT_TYPE = {
  special: ['BOSS', 'PA', 'CAO', 'CSO', 'COO'],
  hr: [
    'CHO',
    'VP OF HR',
    'HR DIRECTOR',
    'SENIOR HR MANAGER',
    'HR MANAGER',
    'HR SUPERVISOR',
    'SENIOR HR EXECUTIVE',
    'HR EXECUTIVE',
    'JUNIOR HR EXECUTIVE',
    'HR INTERN',
  ],
  account: ['CFO', 'FINANCE MANAGER', 'ACCOUNT SUPERVISOR', 'ACCOUNT EXECUTIVE', 'ACCOUNT INTERN'],
  media: [
    'CVO',
    'VP VISUAL',
    'VISUAL DIRECTOR',
    'SR.MEDIA MANAGER',
    'MEDIA MANAGER',
    'MEDIA LEAD',
    'SR.VIDEO CREATOR',
    'VIDEO CREATOR',
    'JR.VIDEO CREATOR',
    'MEDIA INTERN',
  ],
  marketing: [
    'CMO',
    'VP OF MARKETING',
    'MARKETING DIRECTOR',
    'SR.MARKETING MANAGER',
    'MARKETING MANAGER',
    'ASST.MARKETING MANAGER',
    'SR.MARKETING EXEC',
    'MARKETING EXEC',
    'JR.MARKETING EXEC',
    'MARKETING INTERN',
  ],
  support: [
    'VO OF KS',
    'KITCHEN.SUP DIRECTOR',
    'SENIOR KITCHEN SUP MANAGER',
    'KITCHEN SUP MANAGER',
    'KITCHEN SUPPORT LEAD',
    'SENIOR KITCHEN SUPPORT',
    'KITCHEN SUPPORT',
    'JUNIOR KITCHEN SUPPORT',
    'KITCHEN SUPPORT INTERN',
  ],
  production: [
    'VP OF OPERATIONS',
    'OPERATIONS DIRECTOR',
    'SNR.OPERATIONS MANAGER',
    'PRODUCTION MANAGER',
    'TEAM LEAD',
    'SENIOR PRODUCTION',
    'OPERATOR',
    'JUNIOR OPERATOR',
    'OPERATOR INTERN',
  ],
  'r&d': [
    'VP PF R&D',
    'R&D DIRECTOR',
    'SENIOR R&D MANAGER',
    'R&D MANAGER',
    'LEAD R&D',
    'SENIOR R&D',
    'R&D',
    'JUNIOR R&D',
    'R&D INTERN',
  ],
  technical: [
    'CTO',
    'VP OF TECH',
    'TECH DIRECTOR',
    'SR.ENGN.MANAGER',
    'ENG.MANAGER',
    'TECH LEAD',
    'SR.TECH ENGINEER',
    'TECH ENGINEER',
    'JR.TECH ENGINEER',
    'ENGINEER INTERN',
  ],
  design: [
    'CBO',
    'VP OF DESIGN',
    'DESIGN DIRECTOR',
    'SENIOR DESIGN MANAGER',
    'DESIGN MANAGER',
    'DESIGN SUPERVISOR',
    'GRAPHIC DESIGNER',
    'JUNIOR GRAPHIC DESIGNER',
    'DESIGN ASSISTANT',
    'DESIGNER INTERN',
  ],
  operation: ['OPERATION MANAGER'],
  service: [
    'MANAGER',
    'ASST.MANAGER',
    'SUPERVISOR',
    'SENIOR CAPTAIN',
    'CAPTAIN',
    'SENIOR WAITER',
    'WAITER',
  ],
  sushi: ['HEAD CHEF', 'OUTLET CHEF', 'ASST.CHEF', 'COMIS 1', 'COMIS 2', 'COMIS 3', 'SUSHI HELPER'],
  kitchen: ['HEAD CHEF', 'OUTLET CHEF', 'ASST.CHEF', 'COMIS 1', 'COMIS 2', 'COMIS 3', 'KITCHEN HELPER'],
};

export const ACCOUNT_TYPE_OPTIONS = [
  { value: 'special', label: '特殊 (Special)' },
  { value: 'hr', label: '人事部 (HR)' },
  { value: 'account', label: '会计部 (Accountant)' },
  { value: 'media', label: '媒体制作部 (Media Production)' },
  { value: 'marketing', label: '推广部 (Marketing)' },
  { value: 'support', label: '支援部 (Support)' },
  { value: 'production', label: '生产部 (Production)' },
  { value: 'r&d', label: '研发部 (R&D)' },
  { value: 'technical', label: '科技部 (Technical)' },
  { value: 'design', label: '设计部 (Design)' },
  { value: 'operation', label: 'Operation' },
  { value: 'service', label: '前台 (Service)' },
  { value: 'sushi', label: 'Sushi Bar' },
  { value: 'kitchen', label: '厨房 (Kitchen)' },
];

export const BRANCH_OPTIONS = [
  { value: 'kh', label: 'KH' },
  { value: 'j1', label: 'J1 (Midvalley Southkey)' },
  { value: 'j2', label: 'J2 (Paradigm Mall)' },
  { value: 'j3', label: 'J3 (Desa Tebrau)' },
];

export const BRANCH_L1_OPTIONS = [
  { value: 'all', label: '全部' },
  { value: 'kunzz', label: 'KH' },
  { value: 'branch', label: '分店' },
];

export const BRANCH_L2_OPTIONS = [
  { value: 'all', label: '全部分店' },
  { value: 'j1', label: 'J1' },
  { value: 'j2', label: 'J2' },
  { value: 'j3', label: 'J3' },
];

export const DOWNLOAD_COMPANIES = [
  { value: 'KUNZZHOLDINGS', label: 'KUNZZHOLDINGS', file: 'kh.pdf' },
  { value: 'TOKYO_J1', label: 'TOKYO (J1)', file: 'j1.pdf' },
  { value: 'TOKYO_J2', label: 'TOKYO (J2)', file: 'j2.pdf' },
  { value: 'TOKYO_J3', label: 'TOKYO (J3)', file: 'j3.pdf' },
];

export const BANK_OPTIONS = [
  'Maybank (Malayan Banking Berhad)',
  'CIMB Bank',
  'Public Bank',
  'RHB Bank',
  'Hong Leong Bank',
  'AmBank',
  'Alliance Bank',
  'Affin Bank',
  'Bank Islam Malaysia',
  'Agrobank',
  'Bank Simpanan Nasional (BSN)',
  'HSBC Bank Malaysia',
  'OCBC Bank (Malaysia)',
  'Standard Chartered Bank Malaysia',
  'United Overseas Bank (UOB Malaysia)',
  'Bank of China (Malaysia)',
];

export const NATIONALITY_OPTIONS = [
  'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia',
  'China', 'Cyprus', 'East Timor (Timor-Leste)', 'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq',
  'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia',
  'Maldives', 'Mongolia', 'Myanmar (Burma)', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestine',
  'Philippines', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan',
  'Tajikistan', 'Thailand', 'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen',
];

export const RACE_OPTIONS = [
  'Malay', 'Chinese', 'Indian', 'Bumiputera (Sabah/Sarawak)', 'Indonesian', 'Bangladeshi', 'Nepali',
  'Myanmar', 'Filipino', 'Indian (Foreign)', 'Pakistani', 'Vietnamese', 'Cambodian', 'Others (Foreign)',
];
